### ISSUE TITLE
My terminal windows stays in the color of the last generated block.

### ISSUE THREAD

**Issue by N07070** [zzggbb/colorblocks#1]
Hey !

I found a bug : When i Ctrl-C the program, my terminal gets the background color that the last block was in.

![](http://i.imgur.com/E99LMGU.png)

**Comment by ghost** [comment]
should probably catch the KeyboardInterrupt, and clear() before exiting.

**Comment by zzggbb** [comment]
fixed, thanks for pointing this out, and thanks for the suggested fix. 
latest commit:
https://github.com/zzggbb/colorblocks/commit/02e97ae5d1aeb4b82798a6fee24e488a992a9da6
