### ISSUE TITLE
Don't enforce unicode by using "▉"

### ISSUE THREAD

**Issue by Kaligule** [zzggbb/colorblocks#4]
With commit https://github.com/zzggbb/colorblocks/commit/ec888a0e47e482adcbbce9d50b265f7862cafa13 the support for non-unicode terminals is broken, since ▉ can not be displayed. I got the error 

```
Traceback (most recent call last):
  File "./colorblocks.py", line 62, in <module>
    blocks(**vars(parser.parse_args()))
  File "./colorblocks.py", line 44, in blocks
    echo(block(gap, size, row_color, same, char))
  File "./colorblocks.py", line 9, in <lambda>
    echo = lambda s: print(s, end="")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-14: ordinal not in range(128)
```

**Comment by zzggbb** [comment]
Which terminal are you using?

**Comment by Kaligule** [comment]
rxvt and xterm, both didn't work.

**Comment by zzggbb** [comment]
Newest commit drops the necessity for unicode. The program now chooses to set either the background color or foreground color depending on the character used.
https://github.com/zzggbb/colorblocks/commit/c51c31f811b454f5e721d29f1926bdf619c5326e

**Comment by Kaligule** [comment]
Very well done. Thank you.
And in addition, the code looks much better now.
