### ISSUE TITLE
Errors Errors Errors

### ISSUE THREAD

**Issue by aqu0s** [zzggbb/colorblocks#6]
Multiple errors I keep getting:

```
 Scripts » python3 colorblocks.py 
Traceback (most recent call last):
  File "colorblocks.py", line 19, in <module>
    from docopt import docopt
ImportError: No module named 'docopt'

  File "colorblocks.py", line 23
    echo = lambda s: print(s, end="")
                         ^
SyntaxError: invalid syntax
```

**Comment by zzggbb** [comment]
the program switched from argparse to docopt for the argument handling. docopt isn't included with python like argparse, so you need to install it.

```
pip3 install docopt
```

Also that syntax error is strange, I can only reproduce it if I run `python2 colorblocks.py`. Are you sure you have python3 properly installed?
